# Generated by Django 2.0.7 on 2018-09-03 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing_Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('finished', models.BooleanField(default=False)),
                ('players_number', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing_Game_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_price', models.IntegerField()),
                ('profit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('finished', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round', to='main.Pricing_Game')),
            ],
        ),
        migrations.AddField(
            model_name='pricing_game_data',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round', to='main.Round'),
        ),
        migrations.AddField(
            model_name='pricing_game_data',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('round_number', 'game')},
        ),
        migrations.AlterUniqueTogether(
            name='pricing_game_data',
            unique_together={('source', 'round')},
        ),
    ]
