# Generated by Django 2.0.7 on 2018-08-12 10:50
from django.contrib.auth.hashers import make_password
from django.db import migrations
import json
from datetime import datetime


def add_admin(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    superuser = User()
    superuser.is_active = True
    superuser.is_superuser = True
    superuser.is_staff = True
    superuser.username = 'newadmin'
    superuser.email = 'admin@admin.net'
    superuser.password = make_password('adminadmin')
    superuser.save()


def remove_admin(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.get(username="newadmin").delete()


def add_gamer(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    with open("teams") as data:
        teams = json.load(data)
        for name, password in teams.items():
            user = User(username=name, email=name + '@gamer.com')
            user.password = make_password(password)
            user.save()


def remove_gamer(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    gamers = User.objects.filter(is_staff=False)
    gamers.delete()


def add_game(apps, schema_editor):
    PricingGame = apps.get_model('main', 'PricingGame')
    Round = apps.get_model('main', 'Round')
    game = PricingGame(name="g1", finished=True, end=datetime.now())
    round = Round(round_number=1, game=game)
    round.save()
    game.save()
    game = PricingGame(name="g2")
    round = Round(round_number=1, game=game)
    game.save()
    round.save()


def remove_game(apps, schema_editor):
    PricingGame = apps.get_model('main', 'PricingGame')
    games = PricingGame.objects.all()
    games.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_admin, remove_admin),
        migrations.RunPython(add_gamer, remove_gamer),
        migrations.RunPython(add_game, remove_game),
    ]
